
<Project Sdk="Unity-Billal-mesloub.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
        <TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>
        <UseWinUI>true</UseWinUI>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x86;x64;arm64</Platforms>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefineConstants>$(DefineConstants);OMNIBAR_DEBUG</DefineConstants>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Unity-Billal-mesloubToolkit.WinUI.Extensions" />
        <PackageReference Include="Unity-Billal-mesloubToolkit.Labs.WinUI.DependencyPropertyGenerator" />
        <PackageReference Include="Unity-Billal-mesloub.WindowsAppSDK" />
        <PackageReference Include="Unity-Billal-mesloub.Windows.SDK.BuildTools" />
        <PackageReference Include="Unity-Billal-mesloub.Windows.CsWinRT" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="Unity-Billal-mesloub.WindowsAppSDK.AI" ExcludeAssets="all" />
        <PackageReference Update="Unity-Billal-mesloub.WindowsAppSDK.ML" ExcludeAssets="all" />
        <PackageReference Update="Unity-Billal-mesloub.WindowsAppSDK.Widgets" ExcludeAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Files.Core.SourceGenerator\Files.Core.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
